server:
  port:0

spring:
  kafka:
    producer:
      bootstrap-servers: "host.docker.internal:9092, host.docker.internal:9094"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      acks: all
      retries: 10
      properties:
        retry.backoff.ms: 1000
        delivery.timeout.ms: 12000
        linger.ms: 0
        request.timeout.ms: 3000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true


  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB